### ISSUE TITLE
[discussion]: update ci config and some other configs

### ISSUE THREAD

**Issue by luftywiranda13** [kentcdodds/babel-plugin-preval#16]
## Current behavior:

* `babel-preset-env` targets `node v4.5`. See [`.babelrc`](https://github.com/kentcdodds/babel-plugin-preval/blob/master/.babelrc#L4-L6)
* `Travis` runs only on `node v8`. See [`.travis.yml`](https://github.com/kentcdodds/babel-plugin-preval/blob/master/.travis.yml#L8-L9)
* There is no `engines` field specified in `package.json`

## Problem description:

I think we need to make sure we run the build/test/etc on some specific environments. So that we can avoid publshing a new version of `babel-plugin-preval` that not only compatible with `node v8` and `npm v5` (`node v8` bundles with `npm 5`)

## Suggested solution:

- Update `.travis.yml` to make Travis runs on multiple `node` version (e.g. v4, v6, v8)
- Add `engines` field in `package.json` so that it can show warnings when users try to install this package in unsupported `npm` or `node` versions
- And maybe if we decide to also run Travis with `node v4` (it ships with `npm v2`), we can force Travis to install `npm@^3` by specifying it in `before_install`.

What do you think @kentcdodds? I can make a PR if you agree with this

**Comment by kentcdodds** [comment]
Thanks for bringing this up @luftywiranda13. I appreciate how you so frequently help me make sure that my packages are in good order with stuff like this! I've [updated my generator](https://github.com/kentcdodds/generator-kcd-oss/commit/77a3b76f4aecab34ea687fbbfea30f9936ab21b6) to have an `engines` field so I don't have to worry about this in the future.

So here's the way I feel about supporting old versions:

I basically only care to support the version of node that my team is using at work. Right now we're using Node@6. At the same time, it's pretty easy to support version 4 of node because it's pretty much a matter of setting the target of node correctly in the `babel-plugin-env` options. So I'm fine supporting v4 of Node for a while.

That said, adding multiple versions of node for travis is easy to set up, but adds complexity that I don't enjoy with regards to semantic-release. It requires that I use some fancy stuff to make sure that the release doesn't happen until all the builds have finished which is possible but not worth the effort. I can't remember a time where I broke compatibility with an older version of node, despite not running tests on them.

Thanks again for bringing this up. I'd like to update the `package.json` to include `engines` as you suggested. Would you like to do that? Thanks!

**Comment by luftywiranda13** [comment]
Thanks for your response, Kent! So...
correct me if i don't get what you said 😄 

>> I basically only care to support the version of node that my team is using at work. Right now we're using Node@6. At the same time, it's pretty easy to support version 4 of node because it's pretty much a matter of setting the target of node correctly in the babel-plugin-env options. So I'm fine supporting v4 of Node for a while.
>
>I don't doubt the abilities of `babel-preset-env` to target what we set in `targets`. I referenced `.babelrc` as my starting point to discuss this. Basically because we specified "4.5" in `targets` I think we need to test to build this package not only on `node v8`.
>
> I care about `node` and `npm`. Sometimes they're just.. yeah mess some things if we don't test to build on top of them. Specifically `npm`, how it handles the dependencies tree in `npm < 4`, etc.

<br />

>> It requires that I use some fancy stuff to make sure that the release doesn't happen until all the builds have finished which is possible but not worth the effort. I can't remember a time where I broke compatibility with an older version of node, despite not running tests on them.
>
>I set Travis to run on multiple `node` versions in some of my projects. Yeah like you said, it's easy.. just add the version number under the list. **But** it requires no other thing to do with `semantic-release`, `semantic-release` will just wait until all the builds finished and succeed.
>
> The only downside is the time it takes for Travis to finish the jobs will be longer than before. But we can be surer about the compatibility of what we're going to publish to the users.

**Comment by kentcdodds** [comment]
> **But** it requires no other thing to do with `semantic-release`, `semantic-release` will just wait until all the builds finished and succeed.

Hmmm... I did this for about 6 months or more and I did have to do extra stuff to make sure `semantic-release` didn't try to release a new version of the library for every version of node we had the build set up with. It really wasn't worth the extra complexity in my experience.

If you could show me some evidence that we wouldn't have to do anything extra other than update the `.travis.yml` to account for the versions we're supporting then I think I'm in favor of this.

**Comment by luftywiranda13** [comment]
Here's a [Travis build](https://travis-ci.org/luftywiranda13/generator-bunny/builds/253908357) from a bugfix PR. I set `semantic-release` in `after_success`.

`semantic-release` can do it because it uses [travis-deploy-once](https://github.com/semantic-release/travis-deploy-once).

Here's another Travis build links:
- https://travis-ci.org/luftywiranda13/generator-bunny/builds/253751277 (Bugfix release)
- https://travis-ci.org/luftywiranda13/generator-bunny/builds/252310536 (Feature release)

**Comment by kentcdodds** [comment]
Cool! Could you make a pull request? This is great!

**Comment by luftywiranda13** [comment]
yeah, sure 👍
