### ISSUE TITLE
How could I import multiple files with this?

### ISSUE THREAD

**Issue by houshuang** [kentcdodds/babel-plugin-preval#23]
Very interesting plugin! I have an application that allows for plugins as separate NPM packages. Right now, users have to add these manually to a file, first importing them, and then adding them to an array. Example code looks like this:

```js
import acInduction from 'ac-induction';
import acBrainstorm from 'ac-brainstorm';
import acChat from 'ac-chat';

export const activityTypes: Array<ActivityPackageT> = [
  acInduction,
  acBrainstorm,
  acChat
].map(x => Object.freeze(x));
```

I would love to enable users to skip this step, by reading all ac-* packages from the package.json and automatically generating this code, and preval seems like a perfect candidate. However, I couldn't quite figure out how to do this - I can figure out how to get a list of packages, but how to generate the code? Do I build up a string and then eval it, or how can I generate it?

I realize this is not a traditional issue, but I'd really appreciate your feedback. Thanks!

(repo: https://github.com/chili-epfl/FROG)

**Comment by kentcdodds** [comment]
Hi @houshuang!

I'm glad you brought this up. One thing you _could_ do is:

```javascript
// @preval
import acInduction from 'ac-induction';
import acBrainstorm from 'ac-brainstorm';
import acChat from 'ac-chat';

export const activityTypes: Array<ActivityPackageT> = [
  acInduction,
  acBrainstorm,
  acChat
].map(x => Object.freeze(x));
```

And then import that file and it _should_ be all prevaled. But I'm not sure that's what you're going for.

I think what you're hoping for is a code-generation tool. `babel-plugin-preval` is not that, but I've definitely thought about creating a plugin that would do that: [`babel-plugin-codegen`](https://www.npmjs.com/package/babel-plugin-codegen) is available and would probably be pretty similar to `babel-plugin-preval`. I think it'd be pretty cool and I already have a use case for it (get rid of [this file](https://github.com/paypal/glamorous/blob/master/other/concat-exports.js) and just inline that).

If you (or anyone else) want to build that, that'd be super. Otherwise I may build it eventually.

**Comment by kentcdodds** [comment]
`babel-plugin-codegen` exists (I wrote it) and you can use it to do this now :)
