### ISSUE TITLE
Customize string quotation style

### ISSUE THREAD

**Issue by geovanisouza92** [kentcdodds/babel-plugin-preval#25]
- `babel-plugin-preval` version: 1.4.2
- `node` version: v7.8.0
- `npm` (or `yarn`) version: 4.2.0

**Relevant code or config**:

Before:

```javascript
const renderTemplate = (one, two) => `3 === ${one + two}`
```

After:

```javascript
const renderTemplate = (one, two) => preval`
  module.exports = require('fs').readFileSync('./template.js', 'utf8')
`
```

```js
3 === ${one + two}
```

**What you did**:

I moved one template string that I had on a file to another file, and replaced with a _preval_ to read that file.

**What happened**:

It replaced with a string quoted with double quotes.

**Problem description**:

I was expecting to keep the backticks, allowing babel to transpile it correctly later on the pipeline.

**Suggested solution**:

There is a way to customize quotation style or instruct preval which AST string to render?

**Comment by kentcdodds** [comment]
Hi @geovanisouza92, thanks for bringing this up.

Unfortunately, due to the way that preval has to work, we need to convert an object in memory to a string of code. [That process is not easy and a little hacky](https://github.com/kentcdodds/babel-plugin-preval/blob/master/src/object-to-ast.js). Feel free to [improve it](http://makeapullrequest.com/).

**Comment by kentcdodds** [comment]
This isn't really actionable, and I think that you might be able to use [`babel-plugin-codegen`](https://www.npmjs.com/package/babel-plugin-codegen) as it's more powerful and flexible (although a little less ergonomic). Good luck!
