### ISSUE TITLE
Feature request: reusable prevals

### ISSUE THREAD

**Issue by bluepnume** [kentcdodds/babel-plugin-preval#36]
Just wanted to make a quick note of this idea.

Would be really cool if we could define a re-usable preval in code. Right now I have:

```javascript
export let componentStyle = preval`
    module.exports = require('node-sass').renderSync({
        data: \`${ style }\`
    }).css.toString();
`;
```

It would be awesome if I could break this out or alias it into a reusable `prevalSass` or something like that:

```javascript
let prevalSass = prevalAlias`
    module.exports = require('node-sass').renderSync({
        data: \`$input`
    }).css.toString();
`;

export let componentStyle = prevalSass`${ style }`;
```

Not really attached to any particular semantics for this -- just like the idea of being able to write little reusable preval macros.

**Comment by kentcdodds** [comment]
Hey @bluepnume!

I think that you might be able to accomplish this by creating a custom [`babel-macro`](https://github.com/kentcdodds/babel-macros). I don't know how we'd do this in `babel-plugin-preval`. If you have a suggestion let me know, but I'll go ahead and close this because I'm not able to work on it and I don't really see a way for it to be done. Good luck!
