### ISSUE TITLE
"preval file comment" method has no effect on modules that use Strict Mode

### ISSUE THREAD

**Issue by zenflow** [kentcdodds/babel-plugin-preval#47]
* `babel-plugin-preval` version: 1.6.3
* `node` version: 8.5.0
* `npm` (or `yarn`) version: 5.3.0
* (also maybe relevant, but probably not) `@babel/core` version: 7.0.0-beta.38

What you did: Tried to use the "preval file comment" method on a Strict Mode file, e.g.:

```js
// @preval
'use strict';
// ...
```

What happened: The file did not get "prevaled". There was no error or warning.

Reproduction repository: https://github.com/zenflow/preval-use-strict-bug

Problem description: As titled, "preval file comment" method has no effect on modules that use Strict Mode

Suggested solution: No idea... make it work? : D

Thanks @kentcdodds for your work on this and all your other brilliant innovations!

**Comment by kentcdodds** [comment]
Hey @zenflow!

Did you know that if you're using babel, it will add the `'use strict';` pragma for you? You don't need to add it manually. So I'd suggest that you just remove that from any file that's processed by babel :)

Otherwise, feel free to dig in further to see what the problem is, come up with a solution, and [make a pull request](http://makeapullrequest.com) :)

Thanks!

**Comment by kentcdodds** [comment]
I'm going to go ahead and close this issue because I think the workaround is acceptable (just don't manually write `'use strict';`). Feel free to investigate and make a pull request if you really want this fixed!
