### ISSUE TITLE
Can not see console log output

### ISSUE THREAD

**Issue by J-F-Liu** [kentcdodds/babel-plugin-preval#48]
For example,
```
const deploy = preval`
const deploy = process.env.DEPLOY || "local";
console.log("Deploy target:", deploy);
module.exports = deploy;
`;
```

**Comment by kentcdodds** [comment]
Hi @J-F-Liu,
Unfortunately there's not anything we can do on the plugin side. If you're not seeing console log messages it's because the tool that you're using to run you babel transforms is hiding it. NOTE that the console messages will appear in your terminal where you're running your tool, NOT in the browser.

That said, if you would like it to run in the browser (or whatever environment you're running in), you can make that work by using preval's cousin [`codegen`](https://github.com/kentcdodds/babel-plugin-codegen):

```javascript
codegen`
module.exports = \`
  const deploy = process.env.DEPLOY || "local";
  console.log("Deploy target:", deploy);
\`
`;
```

Alternatively, you could simply do:

```javascript
const deploy = preval`
const deploy = process.env.DEPLOY || "local";
module.exports = deploy;
`;
console.log("Deploy target:", deploy);
```

Either way, getting console messages to appear at build time is not something that babel plugins can control for you. It's all dependent on the tools you're using to run the babel transforms.

Good luck!

**Comment by J-F-Liu** [comment]
I'm using Parcel bundler and actually want to see the message in terminal not browser, thanks for your explanation.
