### ISSUE TITLE
[question] Using objects as template placeholders

### ISSUE THREAD

**Issue by rtm619** [kentcdodds/babel-plugin-preval#64]
Hi,

I was trying out preval with NextJS to inline my data during build time.

This is my code:

```
static async getInitialProps() {
    const { data } = await Axios.get(
      "http://localhost:3100/graphql?query={ articles{ name slug } }"
    );
// data.data is an object
    const actualData = preval`
    const allArticles = ${data.data}
    module.exports = allArticles
    `;
    console.log(actualData);
    return { data };
  }
```

When I console log it, it returns an empty object. Am I doing something wrong here?

**Comment by kentcdodds** [comment]
Hi @rtm619,

Remember that preval happens when your build tool compiles your code. So when you actually run the code, preval has already done its thing and is out of your code. So attempting to make your preval code use a value that wont be available until your code is run will not work. From what it looks like you don't need preval here though. You could just rewrite this to be:

```javascript
static async getInitialProps() {
    const { data } = await Axios.get(
      "http://localhost:3100/graphql?query={ articles{ name slug } }"
    );
// data.data is an object
    const actualData = data.data
    console.log(actualData);
    return { data };
  }
```

**Comment by kentcdodds** [comment]
Good luck!

**Comment by garnerp** [comment]
Hi @kentcdodds .

The use case @rtm619 is trying to achieve is to inline the data when doing a next.js export, that way when the site is served from the exported files that the getInitialProps function is returning the inlined content instead of going to the API.  I think the problem is that preval only supports sync and the call here is async.  Any ideas how to potentially do this using preval?

**Comment by kentcdodds** [comment]
Ah, that's tricky. What would probably be best is to have a script that loads the data into a cache before the build so you can get it synchronously during the build.

But if that doesn't work, your code can do `spawn.sync` to run an asynchronous script synchronously. But that would make your build pretty slow.

**Comment by wkentdag** [comment]
@garnerp just stumbled across this issue trying to do the exact same thing. I ended up adding a `prebuild` script that writes the api data to disk, and then updated `getInitialProps` to the following:

```js
static async getInitialProps({ Component, ctx }) {
    let pageProps = {};

    if (Component.getInitialProps) {
      pageProps = await Component.getInitialProps(ctx);
    }

    const content = preval`
      const fs = require('fs');
      const { join } = require('path');
      let data = {};
      try {
        data = JSON.parse(fs.readFileSync(join(__dirname, '../static/data.json'), 'utf8')).data;
      } catch (e) {
        console.error('error fetching data', e);
      }
      module.exports = data;
    `;

    pageProps.content = content;
    return { pageProps };
  }
```
