### ISSUE TITLE
Exporting a certain combination of functions yields SyntaxError

### ISSUE THREAD

**Issue by sorin-davidoi** [kentcdodds/babel-plugin-preval#9]
- `babel-plugin-preval` version: 1.3.2
- `node` version: 8.1.4
- `npm` (or `yarn`) version: 0.5.2 and 0.27.5

Relevant code or config

```javascript
// @preval

const emojione = require('emojione');

module.exports = {
  convert: emojione.convert,
  shortnameToUnicode: emojione.shortnameToUnicode,
};
```

What you did:
Ran `babel file.js`

What happened:

SyntaxError: file.js: Unexpected token, expected , (30:5)

Problem description:

I am trying to do some manual tree shaking for EmojiOne (since it is not exported as a CommonJS module). What is interesting is that if you leave out either one of the exports it works fine.

Suggested solution:
None so far.

**Comment by kentcdodds** [comment]
Yeah, I should probably mention in the README that functions are a little experimental. It's really hard to do this well because we need to serialize the object into a string, then parse that to get an AST. If you can find a more reliable way to convert existing JavaScript objects into an AST that'd be awesome. That happens [here](https://github.com/kentcdodds/babel-plugin-preval/blob/05736a68decb2876e9a4c1926d75e62b82654a3e/src/object-to-ast.js).

As far as debugging, put [the `objectToAST` code](https://github.com/kentcdodds/babel-plugin-preval/blob/05736a68decb2876e9a4c1926d75e62b82654a3e/src/object-to-ast.js#L6-L8) in a `try/catch` and if there's an error log out the `object`.

In fact, I'd happily accept a PR that adds that with a helpful error message.

**Comment by sorin-davidoi** [comment]
Thanks for the hints, found the issue:

```js
return JSON.stringify(object, stringifyReplacer).replace(/"__FUNCTION_START__(.*)__FUNCTION_END__"/g, functionReplacer);
```

This matches greedily, so having two or more functions results in escape characters not getting replaced.

If I add a `?` it works.

```js
return JSON.stringify(object, stringifyReplacer).replace(/"__FUNCTION_START__(.*?)__FUNCTION_END__"/g, functionReplacer);
```

Is this an acceptable fix?

**Comment by kentcdodds** [comment]
Yeah! If you could [makeapullrequest.com](http://makeapullrequest.com) to add that fix as well as a test case for what you've found that'd be awesome! Also a try/catch (and test case) would be appreciated as well :smile:

Let me know if you need help :+1:
